print(f'dit programmaatje deelt drie getallen, voer de getallen in en druk enter')
getal1 = float(input('voer getal 1 in:   '))
getal2 = float(input('voer getal 2 in:   '))
getal3 = float(input('voer getal 3 in:   '))
uitkomst = ((getal1)/(getal2))/(getal3)
#uitkomst_2d = "{:.2f}".format(uitkomst)
#print(f'de uitkomst is {%.2f}.format{uitkomst}')
print(f'de uitkomst is :')
#print(round(uitkomst,2))
#print("%.2f"%(uitkomst))
print("%.4f"%(uitkomst))
